import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import type { GenreType } from "@/types/global";
import { Button } from "@/components/ui/button";

async function fetchGenres(): Promise<GenreType[]> {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
        headers: {
            Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
        }
    });

	const data = await res.json();
    return data.genres;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const genres = await fetchGenres();

	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body>
				<header className="p-4 bg-gray-300 border-b border-gray-400/60">
					<h1 className="text-3xl font-bold">Movie App</h1>
				</header>

				<main className="flex">
					<aside className="w-50 min-h-150 bg-gray-300 p-4 flex flex-col gap-1">
						<Button variant="outline">
							All Genres
						</Button>

						{genres.map(genre => {
							return (
								<Button
									variant="outline"
									key={genre.id}>
									{genre.name}
								</Button>
							);
						})}
					</aside>
					<section className="p-4">{children}</section>
				</main>
			</body>
		</html>
	);
}
